### ISSUE TITLE
마이페이지 > 리뷰 작성 시 후기 최대글자수 체크

### ISSUE THREAD

**Issue by naturej** [KIT-Frontend-Team2/Paradise#105]
### 🐞 Describe

리뷰 작성 시 후기 글자수 500자가 안넘었는데 유효성 검사에 걸립니다.

![localhost_3000_my-page (1)](https://github.com/KIT-Frontend-Team2/Paradise/assets/11881721/ef5e6e1a-0ff2-416e-ae0c-247fb87df675)

### 🌏 Environment

- OS : Window 10
- Browser : Chrome 버전 115.0.5790.171

**Comment by Jihyeong00** [comment]
해결하였습니다 :)
