### ISSUE TITLE
마이페이지에 heigth를 min-height: 100vh를 준 이유가 궁금합니다.

### ISSUE THREAD

**Issue by Jihyeong00** [KIT-Frontend-Team2/Paradise#116]
### 📝 Describe

현재 마이페이지에서는 다음과 같이 추가되어 있습니다.
![image](https://github.com/KIT-Frontend-Team2/Paradise/assets/115636461/2e63890d-3df0-4423-b2e4-0f699e92ec20)

이는 페이지에서 불러올 상품이 없어도 페이지가 지나치게 길어 보이게 할 수도 있습니다.
![image](https://github.com/KIT-Frontend-Team2/Paradise/assets/115636461/60bd4add-d1e2-483c-adc0-aa95667bedc6)

### ✅ Tasks

해당 heigth를 왜 준것인지 궁금합니다. 푸터를 아래에 고정하기 위해서 일부로 추가한 것인지..?

다른 고정된 방법이 없는지 궁금합니다.

**Comment by naturej** [comment]
넵 그때는 마이페이지에 아무 데이터도 없을 때여서 푸터가 지나치게 위로 붙는것 때문에 100vh 넣었던 것 맞구요~ 
지금은 빼도 되겠네요 ! 수정하겠습니다

**Comment by naturej** [comment]
수정완료
