### ISSUE TITLE
메인 푸터가 화면이 클시 화면 바깥으로 여백이 보입니다.

### ISSUE THREAD

**Issue by Jihyeong00** [KIT-Frontend-Team2/Paradise#121]
### 🐞 Describe

![image](https://github.com/KIT-Frontend-Team2/Paradise/assets/115636461/6a32e1c7-8eac-42c7-9f68-e3d97c4ccb8b)

공통 Container에 min-height 속성을 줄 수 있지만 그거보단 다른 좋은 방법이 있을것 같습니다.

### 🌏 Environment

Microsoft Windows 22H2

**Comment by naturej** [comment]
해당 이슈는 제가 확인해보겠습니다.

**Comment by naturej** [comment]
https://github.com/KIT-Frontend-Team2/Paradise/pull/123
에서 수정완료
