### ISSUE TITLE
마이페이지 부분 수정이 필요할 것 같습니다.

### ISSUE THREAD

**Issue by Jihyeong00** [KIT-Frontend-Team2/Paradise#130]
### 🔨 Describe

1. 페이지네이션과 상품이 매우 가깝습니다. (해결)
![image](https://github.com/KIT-Frontend-Team2/Paradise/assets/115636461/a595fcb2-bcf4-4925-98ce-7d9d329be1c0)

2. 마이페이지에서는 페이지 이동을 변수로 이동을 합니다. 하지만 page를 통해서 요청을 하는 것이 등록상품만 있는 것이 아닙니다. 리뷰또한 페이지를 통해서 요청을 합니다.

현재 관심 상품의 경우 1페이지에는 게시물들이 존재하는 상황입니다. 하지만 기존에 등록상품에서 4페이지로 이동을 하고난 뒤에 다른 페이지를 사용하는 관심 상품이나 리뷰 관리에 들어가게 될 경우 아무것도 보여주지 못합니다. 여기서 문제가 발생합니다. 

![image](https://github.com/KIT-Frontend-Team2/Paradise/assets/115636461/16b9833a-b3e0-4078-a3f8-ebba0a70de1f)

현재 리뷰 페이지의 경우  페이지를 url을 통해서 임의로 변경하게 할 경우 에러페이지가 띄워지도록 설정이 되어져 있습니다. 

사용자의 관점에서 보았을때 페이지 이동을 했을때 이전에 설정해 뒀던 페이지가 그대로 이어지는게 맞는지 생각해봐야할거 같습니다.

### ✅ Tasks

1. 페이지네이션과 상품을 분리  (해결)

2. 마이페이지 내에서 활동 이동시에 페이지를 1페이지로 변경해주기

**Comment by uniend** [comment]
1. 어제 밤에 올린 pr에 간격 띄어놨습니다.
2. 그 부분 해결할려고 시도를 몇번 해봤는데 잘 안되네여 ㅠㅠㅠㅠㅠㅠ

**Comment by Jihyeong00** [comment]
useEffect를 통해서 page를 변경해준것도 방법이 될 수 있을꺼 같아요
