### ISSUE TITLE
공용 레이아웃이 수정되어야 합니다.

### ISSUE THREAD

**Issue by Jihyeong00** [KIT-Frontend-Team2/Paradise#55]
### 🐞 Describe
헤더가 이상하게 가려집니다.
![image](https://github.com/KIT-Frontend-Team2/Paradise/assets/115636461/ee945903-e372-49ed-a88b-a278122c173e)

모바일 푸터가 지도에서 가려집니다. footer 해결해주세요
![image](https://github.com/KIT-Frontend-Team2/Paradise/assets/115636461/92f6592a-493d-4cda-9bc0-f3ede5cf733e)

### 🌏 Environment

모바일 화면에서 보였을때 푸터가 가려집니다.

### 🙋🏻 More

수정해주세요 :)

**Comment by dbs271** [comment]
해결했습니다!
