### ISSUE TITLE
마이페이지 수정 요청

### ISSUE THREAD

**Issue by Jihyeong00** [KIT-Frontend-Team2/Paradise#58]
### 📝 Describe

이메일이 수정이 안될경우 해당 input 박스를 빼면 안될까요? 빼는게 더 예쁠것 같습니다.
![image](https://github.com/KIT-Frontend-Team2/Paradise/assets/115636461/6026bb06-ce50-4bf6-b8eb-26108046066d)

### ✅ Tasks

사용이 안되는 input 태그를 굳이 폼 데이터에 넣어야 하는지 생각이 듭니다.

**Comment by uniend** [comment]
readonly로 변경하고 *표시를 빼고 선택 못하게 막아뒀습니다.!
