### ISSUE TITLE
마이페이지 회의 

### ISSUE THREAD

**Issue by uniend** [KIT-Frontend-Team2/Paradise#60]
### 📝 Describe

1. 마이페이지 
ㄴ 모바일에는 마이헤더 등록상품 관심상품 채팅을 미노출 
ㄴ 메뉴 바에 채팅을 넣어서 두줄로 해야할지 의견 

### ✅ Tasks

1. 모바일 마이헤더 등록상품 관심상품 채팅을 미노출

### 🙋🏻 More

메뉴 바에 채팅을 넣어서 두줄로 해야할지 의견  
ㄴ 사이트 하단에 채팅아이콘이 있고 모달로 뜨는 걸로 알고 있는데 넣어야할까요???

**Comment by Jihyeong00** [comment]
![image](https://github.com/KIT-Frontend-Team2/Paradise/assets/115636461/f4fd1030-102a-4998-a5f8-e75a49d3dcb6)
마이페이지 내의 등록한 물품의 이미지를 클릭하였을 경우 해당 물품의 상세 페이지로 가지면 좋을 것 같습니다.

물품들의 이미지가 작거나 가로가 길경우 해당 카드가 줄어들어 보일 수 있습니다. 해당 부분은 카드의 이미지 부분을 크기를 고정으로 주셔야 합니다.!

**Comment by uniend** [comment]
상세페이지 이동 진행하겠습니다.  ~ 
카드 부분 고정 할게여!

**Comment by Jihyeong00** [comment]
각 카드마다 default 이미지를 주는것도 좋습니다. 현재 모든 상품을 등록할때마다 기본 이미지를 넣게 되어있지만 가끔 안들어가있는 상품이 있습니다. 이러한 경우 대체 이미지를 주며 좋습니다. 
![image](https://github.com/KIT-Frontend-Team2/Paradise/assets/115636461/2004e454-3dfe-45b2-9867-21099fe00705)

**Comment by Jihyeong00** [comment]
![image](https://github.com/KIT-Frontend-Team2/Paradise/assets/115636461/6bb89158-6350-49b0-be6d-7ac00ee92956)
상품 카드를 따라가지 않아 css가 기존의 카드를 벗어나는 경우가 있습니다. 해당 부분 수정 부탁드립니다.,
