### ISSUE TITLE
물품 등록페이지 가격 최대치 요청

### ISSUE THREAD

**Issue by Jihyeong00** [KIT-Frontend-Team2/Paradise#66]
### 📝 Describe

상품의 가격이 터무니없이 높은 가격일 경우 나머지 상품들의 css나 디자인을 변경을 시켜야 합니다. 최대 9999만 정도로 제한을 두었으면 좋겠습니다.

### ✅ Tasks

 상품을 등록할 때의 가격을 최대 9999만 정도로 제한을 두었으면 좋겠습니다.

**Comment by naturej** [comment]
1억원 이상 등록 못하도록 조건 추가했습니다!
