### ISSUE TITLE
헤더 부분 작업이 어떻게 되고있을까요~?

### ISSUE THREAD

**Issue by Jihyeong00** [KIT-Frontend-Team2/Paradise#67]
### 📝 Describe

기존에 얘기했었던 헤더부분에 추가될 사항입니다. 
![image](https://github.com/KIT-Frontend-Team2/Paradise/assets/115636461/14c91399-00bd-45a7-bba3-5971638d55f9)

메인페이지(넣고 안넣고 자유)/ 판매상품 / 중고상품 / 마이페이지

또한 카테고리별로 이동할 때 해당 상품의 영어 키워드가 아닌 검색으로 가야하기 때문에 해당 카테고리의 이름 그대로 페이지이동 함수에 넣어주세요

### ✅ Tasks

1. 메인페이지 상위 헤더 카테고리를 수정해주세요

메인페이지(넣고 안넣고 자유)/ 판매상품 / 중고상품 / 마이페이지

2. 카테고리를 눌렀을 때 페이지가 이동이 되게 수정해주세요

카테고리별로 이동할 때 해당 상품의 영어 키워드가 아닌 검색으로 가야하기 때문에 해당 카테고리의 이름 그대로 페이지이동 함수에 넣어주세요

### 🙋🏻 More

pr 많이 해주세요 진행상황이 공유가 안되고 있습니다. 회의때 얘기했던 레이아웃이 어느 부분이 수정이 되었는지 안되었는지 모르겠어요~

**Comment by dbs271** [comment]
중고상품의 경우 메인페이지에 우리동네 중고상품의 url에 맞춰 SellList로 설정해뒀습니다. 그런데 판매상품 부분은 해당 유저가 올린 판매상품들로 생각하면 되나요? linkUserProduct 이 함수를 사용하는 것이 맞는지 확인 부탁드립니당

**Comment by Jihyeong00** [comment]
저희 필터가 무료상품과 중고상품 판매로 나뉘어 집니다. 무료나눔 상품이 아닌 판매나눔 상품을 얘기하는겁니다!

**Comment by Jihyeong00** [comment]
1. 헤더 카테고리 버튼을 누를경우 이동이 언제쯤 되는걸까요? 
2. 마이페이지 이동을 할 때 혼자서 다른 url로 이동이 되기 때문에 오류가 불러 일으켜집니다. url 수정 가능할까요~?
3. 로고 이미지가 너무 작아서 화질이 좀 안좋게 나오는것 같습니다. 로고 이미지를 수정하거나 혹은 그저 텍스트 태그 안에 text-size를 크게해서 보여주는게 어떨까요~? wanted와 같이 하는것이 좋을 것 같습니다.
