### ISSUE TITLE
렌딩페이지 요청사항

### ISSUE THREAD

**Issue by Jihyeong00** [KIT-Frontend-Team2/Paradise#73]
### 📝 Describe

1. 렌딩 페이지 로그인하러가기 버튼 위치 조정 또는 추가 요청
2. 자동로그인을 구현을 하였습니다 하지만 렌딩페이지가 적은시간동안 이지만 보입니다. 혹시 배경화면을 약간 0.5초정도 흰 화면에서 띄워지는 식으로 변경 가능할까요?

### ✅ Tasks

1. 렌딩페이지는 현재 로그인을 하지 않았을경우 가지는 페이지입니다. 대신 로그인 회원가입을 하려면 스크롤을 내려야하는데 좀 오래걸리고 힘든것 같습니다. 처음 화면에 바로 로그인 회원가입을 하러가면 좋을것 같습니다.
2. 배경화면을 약간 0.5초정도 흰 화면에서 띄워지는 식으로 변경 가능할까요? 배경화면이 보일수밖에 없습니다..

**Comment by naturej** [comment]
1번 : 랜딩페이지 상단에도 로그인 버튼 넣었습니다!
