### ISSUE TITLE
물품 리스트 모바일에서 2열로 변경 요청

### ISSUE THREAD

**Issue by naturej** [KIT-Frontend-Team2/Paradise#96]
### 📝 Describe

저희 모바일에서는 물품 리스트가 2열로 나오게 하도록 정했었습니다.

예시
<img width="428" alt="image" src="https://github.com/KIT-Frontend-Team2/Paradise/assets/11881721/32543f93-dd9f-4dc6-8c93-488f1d481a49">

### ✅ Tasks

요청사항
- 모바일 리스트에서 물품 2열로 변경 (현재 상품 1열로 노출)
- 고정 width가 아닌 가변형 width로 변경 (현재 250px 고정)

**Comment by Jihyeong00** [comment]
해당 내용들 전부 수정하였습니다!
