### ISSUE TITLE
물품 상세 페이지 css 수정 요청

### ISSUE THREAD

**Issue by naturej** [KIT-Frontend-Team2/Paradise#97]
### 📝 Describe

물품 상세 페이지의 
좌측 물품 썸네일 영역과 
우측 물품 정보 영역의 크기가 50%로 동일하게 되어있습니다.

시안처럼 썸네일 영역 크기를 최대 500px로 바꿔주셨으면 좋겠습니다. (이미지가 너무 커요..ㅠ)

![image](https://github.com/KIT-Frontend-Team2/Paradise/assets/11881721/6da277fd-704d-4d29-98d4-99f2ad5f04ce)

![image](https://github.com/KIT-Frontend-Team2/Paradise/assets/11881721/97e16fb5-0a55-4bee-9a7d-19119fa8fca3)

### ✅ Tasks

- 썸네일 영역 최대 넓이 500px
- 좌우 사이 간격 조정 (현재 20px, 시안은 59px인데.. 30px 정도로 해도 좋을 것 같습니다)
- 가능하다면 금액에서 '원'만 28p로 변경해주시면 좋겠습니다.

**Comment by Jihyeong00** [comment]
넵 확인하였습니다! 수정후 올려드리겠습니다

**Comment by Jihyeong00** [comment]
해당 내용들 전부 수정하였습니다!
